# Operaciones aritméticas entre vectores, matrices y arreglos multidimensionales

In [1]:
import numpy as np

## Definiendo matrices iniciales

In [14]:
mat_x = np.array([[2, 4], [6, 10]])
mat_y = np.array([[3, 5], [7, 10]])

In [15]:
mat_x

array([[ 2,  4],
       [ 6, 10]])

In [16]:
mat_y

array([[ 3,  5],
       [ 7, 10]])

## Adición (Suma de matrices)

In [17]:
mat_x + mat_y

array([[ 5,  9],
       [13, 20]])

## Sustracción (Resta de matrices)

In [18]:
mat_y - mat_x

array([[1, 1],
       [1, 0]])

## Multiplicación

Notemos que con este operador se multiplican solamente la entrada i-esima, j-esima de cada matriz, por lo tanto no es la multiplicación de matrices

In [19]:
mat_y * mat_x

array([[  6,  20],
       [ 42, 100]])

# División

Notemos que con este operador se dividen solamente la entrada i-esima, j-esima de cada matriz 

In [20]:
mat_y / mat_x

array([[1.5       , 1.25      ],
       [1.16666667, 1.        ]])

## Multiplicación con constantes

In [25]:
mat_w = np.array([[2, 4, 6],
                  [6, 10, 14],
                  [9, 12, 15]])

In [26]:
mat_w

array([[ 2,  4,  6],
       [ 6, 10, 14],
       [ 9, 12, 15]])

In [27]:
2 * mat_w # Si conserva la propiedad de constante por matrix

array([[ 4,  8, 12],
       [12, 20, 28],
       [18, 24, 30]])

In [29]:
2 ** mat_w #Eleva el 2 a cada entrada de la matrix, obteniendo una nueva matrix

array([[    4,    16,    64],
       [   64,  1024, 16384],
       [  512,  4096, 32768]], dtype=int32)

## Remodelar

In [32]:
array_x = np.array([1, 2, 3, 4]).reshape(2, 2)
array_y = np.array([1, 2, 3, 4])

In [33]:
array_x

array([[1, 2],
       [3, 4]])

In [34]:
array_y

array([1, 2, 3, 4])

## Concatenación de vectores para crear una matrix

In [36]:
z1 = np.array([[2, 4]])
z2 = np.array([[5, 6]])

z3 = np.concatenate([z1,z2],axis=0)

In [37]:
z1

array([[2, 4]])

In [38]:
z2

array([[5, 6]])

In [39]:
z3

array([[2, 4],
       [5, 6]])

In [40]:
z2.shape # Dimensiones del vector 

(1, 2)

## Selección de funciones en NumPy para funciones matemáticas

In [50]:
x = np.linspace(start = -1, stop = 1, num = 10)

In [51]:
x

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [61]:
np.sqrt(x) # Raiz cuadrada

C:\Users\ALEJAN~1\AppData\Local\Temp/ipykernel_7560/2391977642.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(x) # Raiz cuadrada


array([       nan,        nan,        nan,        nan,        nan,
       0.33333333, 0.57735027, 0.74535599, 0.8819171 , 1.        ])

In [62]:
np.exp(x) # Funcion exponencial

array([0.36787944, 0.45942582, 0.57375342, 0.71653131, 0.89483932,
       1.11751907, 1.39561243, 1.742909  , 2.17662993, 2.71828183])

In [63]:
np.log(x) # Funcion logaritmo natural

C:\Users\ALEJAN~1\AppData\Local\Temp/ipykernel_7560/1277889159.py:1: RuntimeWarning: invalid value encountered in log
  np.log(x)


array([        nan,         nan,         nan,         nan,         nan,
       -2.19722458, -1.09861229, -0.58778666, -0.25131443,  0.        ])

In [64]:
np.log10(x)

C:\Users\ALEJAN~1\AppData\Local\Temp/ipykernel_7560/1114196279.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(x)


array([        nan,         nan,         nan,         nan,         nan,
       -0.95424251, -0.47712125, -0.25527251, -0.10914447,  0.        ])

## Funciones trigonométricas

In [56]:
np.cos(x) #coseno

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [57]:
np.sin(x) # seno

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [58]:
np.arccos(x) # arccoseno

array([3.14159265, 2.46191883, 2.1598273 , 1.91063324, 1.68213734,
       1.45945531, 1.23095942, 0.98176536, 0.67967382, 0.        ])

In [59]:
np.arctan(x) # arcotangente

array([-0.78539816, -0.66104317, -0.5070985 , -0.32175055, -0.11065722,
        0.11065722,  0.32175055,  0.5070985 ,  0.66104317,  0.78539816])

## Aplicando funciones

In [65]:
def funcion_heaviside(x):
    return 1 if x>0 else 0

In [66]:
funcion_heaviside(-1)

0

In [67]:
funcion_heaviside(1)

1

In [72]:
funcion_heaviside(np.linspace(-3,3,7))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [73]:
funcion_heaviside_vectorize = np.vectorize(funcion_heaviside)

In [74]:
funcion_heaviside_vectorize(np.linspace(-3,3,7))

array([0, 0, 0, 0, 1, 1, 1])

## Funciones NumPy para calcular agregados de matrices NumPy 

In [75]:
data_score = np.array([8,9,8,9,10,10,10,6,5,6,7,8,7,8,7,8,8,5,8,9,6,6])

In [83]:
data_score

array([ 8,  9,  8,  9, 10, 10, 10,  6,  5,  6,  7,  8,  7,  8,  7,  8,  8,
        5,  8,  9,  6,  6])

In [76]:
np.mean(data_score) # Promedio de un vector

7.636363636363637

In [78]:
np.std(data_score) # Desviacion estandar de un vector

1.4937887931959075

In [79]:
np.var(data_score) # Varianza de un vector

2.231404958677686

In [80]:
np.sum(data_score) # Suma de todos los elementos de un vector

168

In [84]:
np.min(data_score) # Elemento minimo de un vector

5

In [85]:
np.max(data_score) # Elemento maximo de un vector

10

In [86]:
np.argmin(data_score) # Indice donde se encuentra el valor minimo

8

In [87]:
np.argmax(data_score) # Indice donde se encuentra el valor maximo

4

In [88]:
np.all(data_score) # ¿Todos los elementos son mayores a 0?

True

In [89]:
np.any(data_score) # Devuelve True si alguno de los elementos de la matriz de argumentos es distinto de cero. 

True

In [90]:
np.unique(data_score) # Devuelve elementos unicos de un vector

array([ 5,  6,  7,  8,  9, 10])

## Multiplicación de matrices

In [91]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)

In [92]:
A # Matrix de tamaño 2X3

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
B # Matrix de tamaño 3X2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
np.dot(A,B) # Matrix de tamaño 2X3

array([[22, 28],
       [49, 64]])

## Inversa de una matrix

In [110]:
Z = np.random.rand(3,3)

In [111]:
Z

array([[0.20303049, 0.2461013 , 0.19520462],
       [0.2500264 , 0.3359148 , 0.15193434],
       [0.29422468, 0.95489   , 0.84286774]])

In [114]:
Z_inv = np.linalg.inv(Z)

In [116]:
np.round(Z.dot(Z_inv))

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0.,  0.,  1.]])