# Creando vectores, matrices y arreglos multidimensionales

In [2]:
import math as mathlib
import numpy as np

In [5]:
data = np.array([[1, 2], [3, 4], [5, 6]])

## Clases de array (atributos)

In [7]:
print(type(data))

<class 'numpy.ndarray'>


In [8]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
data.ndim #Numero de dimensiones del arreglo

2

In [15]:
data.shape #Forma del arreglo

(3, 2)

In [11]:
data.size #Tamaño del arreglo

6

In [16]:
data.dtype #Tipo de información numerica

dtype('int32')

In [17]:
data.nbytes

24

### Tipos de arreglos

In [19]:
np.array([1, 2, 3], dtype=int) #Entero

array([1, 2, 3])

In [21]:
np.array([1, 2, 3], dtype=float) #Flotante

array([1., 2., 3.])

In [25]:
array_complex = np.array([1, 2, 3], dtype=complex) #Numeros complejos
array_complex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
array_complex.real #Parte real

array([1., 2., 3.])

In [27]:
array_complex.imag

array([0., 0., 0.])

In [31]:
np.zeros(shape = 10,dtype=int) #Crea un vector de 10 elementos de valor 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.zeros(shape = (5, 3) , dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.ones(shape = 10,dtype=int) #Crea un vector de 10 elementos de valor 1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
np.ones(shape = (3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
array_example = np.array([1,2,3,6,5,4]) #Crea una diagonal con un vector dado, las demas entradas son 0
np.diag(array_example)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 4]])

In [42]:
np.arange(8) # Crea un vector de 0 a n

array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
np.arange(3,9) # Crea un vector de iniciando en a hasta b

array([3, 4, 5, 6, 7, 8])

In [45]:
np.arange(3,7,0.5)# Crea un vector de iniciando en a hasta b con pasos de c

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [46]:
np.linspace(2.0, 3.0, num=10) #Similar a arange

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [49]:
np.linspace(start = 2.0, stop = 3.0, num=10, endpoint= False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [54]:
np.random.rand(10) #Crea un arreglo de de tamaño 10 con numeros aleatorios (numeros uniformes en 0 a 1)

array([0.7233541 , 0.47887605, 0.22317457, 0.19275188, 0.11063909,
       0.04135065, 0.94182316, 0.28238057, 0.21441154, 0.78276593])

## Ejemplos de expresiones de segmentación y indexación de matrices 

In [58]:
array_test = np.array([1,2,9,8,43,5,6,8,8,9,0,12])

In [59]:
array_test[4] #Muestra el elemento en el indice 4 (Recordando que un array empieza con indice 0)

43

In [62]:
array_test[-2] #Muestra el elemento 2 del final hacia atras

0

In [64]:
array_test[1:4] #Muestra los elementos en el indice 1 al 4

array([2, 9, 8])

In [65]:
array_test[:] #Muestra todos los elementos del array

array([ 1,  2,  9,  8, 43,  5,  6,  8,  8,  9,  0, 12])

In [69]:
array_test[0:] #Muestra todos los elementos del array (similar al anterior)

array([ 1,  2,  9,  8, 43,  5,  6,  8,  8,  9,  0, 12])

In [70]:
array_test[2:6:2] #Muestra todos los elementos en el indice 2 al 6 en incrementos de 2

array([ 9, 43])

In [71]:
array_test[::-1] #Invierte el arreglo

array([12,  0,  9,  8,  8,  6,  5, 43,  8,  9,  2,  1])

## Arreglos Multidimensionales

In [81]:
function_to_apply = lambda m, n: n + 10 * (m+1)
A = np.fromfunction(function_to_apply, (9, 6), dtype=int)
A

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [60, 61, 62, 63, 64, 65],
       [70, 71, 72, 73, 74, 75],
       [80, 81, 82, 83, 84, 85],
       [90, 91, 92, 93, 94, 95]])

In [82]:
A[:, 1] # segunda columna

array([11, 21, 31, 41, 51, 61, 71, 81, 91])

In [83]:
A[1, :] # segundo renglon

array([20, 21, 22, 23, 24, 25])

In [84]:
A[:3, :3] 

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [86]:
A[3:, :4]

array([[40, 41, 42, 43],
       [50, 51, 52, 53],
       [60, 61, 62, 63],
       [70, 71, 72, 73],
       [80, 81, 82, 83],
       [90, 91, 92, 93]])

## Indexación elegante e indexación con valores booleanos 

In [87]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [89]:
A[A >= 0.5]

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])