# Programación lineal con Scipy

In [14]:
from scipy.optimize import linprog
import numpy as np

$$
max \text{    } 700x_{1} + 900x_{2} \\
\text{sujeto a}
\\
3x_{1}+ 5x_{2} \leq 3600 \\
x_{1}+ 2x_{2} \leq 1600 \\
50x_{1}+ 20x_{2} \leq 48000 \\
$$

In [27]:
c = [-700, -900] # Recuerda para max f(x) <-> min -f(x)

A = [[3, 5],
     [1, 2],
     [50,20]]
b = [3600, 1600,48000]

x1_bounds = (None, None)
x2_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[x1_bounds, x2_bounds])

In [28]:
res.x # Valores optimos

array([884.21050528, 189.47367975])

In [29]:
res.fun # Valor de la función objetivo

-789473.6654672713

In [30]:
np.dot(np.transpose(res.x),c) # Comprobando manualmente

-789473.6654672713

Veamos el siguiente caso

$$
min \text{    } x_{1} + x_{2} + x_{3} + x_{4} + x_{5} + x_{6} + x_{7}\\
\text{sujeto a}
\\
\begin{matrix}
x_{1} & & & +x_{4} & +x_{5} & +x_{6} & +x_{7} &\geq 110\\
x_{1} & +x_{2} &  & & +x_{5} & +x_{6} & +x_{7} &\geq 80\\
x_{1} & +x_{2} & +x_{3} & & & +x_{6} & +x_{7} &\geq 150\\
x_{1} & +x_{2} & +x_{3} & +x_{4} & & & +x_{7} &\geq 30\\
x_{1} & +x_{2} & +x_{3} & +x_{4} & +x_{5} & & &\geq 70\\
& x_{2} & +x_{3} & +x_{4} & +x_{5} & +x_{6} & &\geq 160\\
 &  & x_{3} & +x_{4} & +x_{5} & +x_{6} & +x_{7} &\geq 120\\
\end{matrix}
$$

In [44]:
c = [1,1,1,1,1,1,1]

A = [[1,0,0,1,1,1,1],
     [1,1,0,0,1,1,1],
     [1,1,1,0,0,1,1],
     [1,1,1,1,0,0,1],
     [1,1,1,1,1,0,0],
     [0,1,1,1,1,1,0],
     [0,0,1,1,1,1,1]]

b = [110,80,150,30,70,160,120]

x1_bounds = (0, None)
x2_bounds = (0, None)
x3_bounds = (0, None)
x4_bounds = (0, None)
x5_bounds = (0, None)
x6_bounds = (0, None)
x7_bounds = (0, None)

In [45]:
A

[[1, 0, 0, 1, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1],
 [1, 1, 1, 0, 0, 1, 1],
 [1, 1, 1, 1, 0, 0, 1],
 [1, 1, 1, 1, 1, 0, 0],
 [0, 1, 1, 1, 1, 1, 0],
 [0, 0, 1, 1, 1, 1, 1]]

In [46]:
np.multiply(A,-1)

array([[-1,  0,  0, -1, -1, -1, -1],
       [-1, -1,  0,  0, -1, -1, -1],
       [-1, -1, -1,  0,  0, -1, -1],
       [-1, -1, -1, -1,  0,  0, -1],
       [-1, -1, -1, -1, -1,  0,  0],
       [ 0, -1, -1, -1, -1, -1,  0],
       [ 0,  0, -1, -1, -1, -1, -1]])

In [39]:
np.multiply(b,-1)

array([-110,  -80, -150,  -30,  -70, -160, -120])

In [40]:
A = np.multiply(A,-1)
b = np.multiply(b,-1)

res = linprog(c, A_ub=A, b_ub=b, bounds=[x1_bounds,x2_bounds,x3_bounds,x4_bounds,x5_bounds,x6_bounds,x7_bounds])

In [41]:
res.x

array([3.33333333e+00, 1.82539464e+01, 3.50793870e+01, 6.74751155e+00,
       6.58582178e+00, 9.33333332e+01, 3.97383729e-08])

In [42]:
res

     con: array([], dtype=float64)
     fun: 163.3333332757294
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([-4.68098733e-08,  4.15064348e+01, -5.64971288e-08,  3.34141782e+01,
       -1.16336452e-08, -9.76096146e-08,  2.17460536e+01])
  status: 0
 success: True
       x: array([3.33333333e+00, 1.82539464e+01, 3.50793870e+01, 6.74751155e+00,
       6.58582178e+00, 9.33333332e+01, 3.97383729e-08])